### ISSUE TITLE
Mock fora do ar

### ISSUE THREAD

**Issue by ArthurGomesp** [PicPay/picpay-desafio-backend#36]
Mock para simular autorização está fora do ar
(https://run.mocky.io/v3/8fafdd68-a090-496f-8c9a-3442cf30dae6)

**Comment by iamthepoe** [comment]
Sim, aconteceu comigo enquanto fazia o desafio. Criei esse novo com base no vídeo da @Fernanda-Kipper 

https://run.mocky.io/v3/5794d450-d2e2-4412-8131-73d0293ac1cc

Retorno: `
{
  "message": "Autorizado"
}
`

Código HTTP: `200`

**Comment by Fernanda-Kipper** [comment]
Pois é! O mock está fora do ar mesmo, eu tinha pego ele diretamente aqui do desafio... 

Mas criei um novo para utilizarmos no video: https://run.mocky.io/v3/9b89b419-a2f7-4885-aa86-5ddcea24d520

Mesmo retorno de antes, e igual ao criado pelo @iamthepoe  

Response: **`{ "message": "Autorizado" }`**

Status HTTP: **`200`**

@iamthepoe boa ideia!
Eu vou colocar lá na descrição do video esse link que eu que criei para quem enfrentar o mesmo problema que assim consigo manter o controle :)

**Comment by leocavalcante** [comment]
Resolvido na https://github.com/PicPay/picpay-desafio-backend/pull/40
